// USER_SEARCH
export const SEARCH_USER_REQUEST = "SEARCH_USER_REQUEST";
export const SEARCH_USER_PROGRESSING = "SEARCH_USER_PROGRESSING";
export const SEARCH_USER_SUCCEEDED = "SEARCH_USER_SUCCEEDED";
export const SEARCH_USER_FAILED = "SEARCH_USER_FAILED";

// FETCH_USER
export const FETCH_USER_REQUEST = "FETCH_USER_REQUEST";
export const FETCH_USER_PROGRESSING = "FETCH_USER_PROGRESSING";
export const FETCH_USER_SUCCEEDED = "FETCH_USER_SUCCEEDED";
export const FETCH_USER_FAILED = "FETCH_USER_FAILED";
