// USER_SEARCH
export const SEARCH_USER_REQUEST = "app/search/SEARCH_USER_REQUEST";
export const SEARCH_USER_PROGRESSING = "app/search/SEARCH_USER_PROGRESSING";
export const SEARCH_USER_SUCCEEDED = "app/search/SEARCH_USER_SUCCEEDED";
export const SEARCH_USER_FAILED = "app/search/SEARCH_USER_FAILED";

// FETCH_USER
export const FETCH_USER_REQUEST = "app/profile/FETCH_USER_REQUEST";
export const FETCH_USER_PROGRESSING = "app/profile/FETCH_USER_PROGRESSING";
export const FETCH_USER_SUCCEEDED = "app/profile/FETCH_USER_SUCCEEDED";
export const FETCH_USER_FAILED = "app/profile/FETCH_USER_FAILED";

// FETCH_USER_REPOS
export const FETCH_USER_REPOS_REQUEST = "app/profile/FETCH_USER_REPOS_REQUEST";
export const FETCH_USER_REPOS_PROGRESSING =
  "app/profile/FETCH_USER_REPOS_PROGRESSING";
export const FETCH_USER_REPOS_SUCCEEDED =
  "app/profile/FETCH_USER_REPOS_SUCCEEDED";
export const FETCH_USER_REPOS_FAILED = "app/profile/FETCH_USER_REPOS_FAILED";
